# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qtreeCPP <- function(pred, resp, minDev, minCut, minSize, tau) {
    .Call(`_qrandomForest_qtreeCPP`, pred, resp, minDev, minCut, minSize, tau)
}

rcpp_hello <- function() {
    .Call(`_qrandomForest_rcpp_hello`)
}

